test-failure-policy: Avoid `\n` in f-string substitution
That doesn't yet work in RHEL 9's Python 3.9:

    SyntaxError: f-string expression part cannot include a backslash

This broke naughty detection in tmt tests.