tests-invoke: Don't break tests on socket errors during collision detection
Tests occasionally fail with

    socket.gaierror: [Errno -3] Temporary failure in name resolution

while running. This ruins the whole test, which is not worth the trouble
at all. Ignore that exception just as we already ignore timeouts.