lib: kill podman run --init if podman rm fails
In CI `podman run` sometimes fails to stop a container with:

Error: reading CIDFile: open /tmp/tmpw4b91s99/cidfile: no such file or directory

The job-runner is then stuck in `gather_and_cancel` waiting on
`task.cancel()` for `create_container` as this is stuck due to a bug
kill the process.

`create_container` itself hangs on:

futex(0x5575a9ff4580, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc00077c148, FUTEX_WAKE_PRIVATE, 1) = 1