tests-scan: fix running without pika
We go out of our way to make sure we don't hard-depend on `pika` being
installed, but then we go right ahead and unconditionally access the
`pika` symbol via a type annotation, triggering this error:

    Traceback (most recent call last):
      File "/var/home/lis/src/bots/main/./tests-scan", line 89, in <module>
        def queue_test(entry: QueueEntry, channel: pika.channel.Channel, options: argparse.Namespace) -> None:
                                                   ^^^^
    NameError: name 'pika' is not defined

Quote the annotation to avoid the issue.