task: Treat SSLEOFError as transient failure
Recently this started to happen annoyingly often:

   ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

This is some transient networking flake or GitHub protocol error. This
breaks otherwise successful image builds+uplodas or test runs at the
very last moment when posting the result to GitHub, and requires manual
retries, which is too expensive.

Fixes #3474