images: don't assume libvirt networking is disabled
The incoming ubuntu-stable image update contains a new version of
libvirt with the following change:

    - Autostart default bridged network (As upstream does, but not Debian).

This causes our unconditional attempt to enable the network to fail with
the following message:

    + virsh net-autostart default
    error: failed to mark network default as autostarted
    error: Failed to create symlink '/etc/libvirt/qemu/networks/autostart/default.xml' to '/etc/libvirt/qemu/networks/default.xml': File exists

Allow for both possibilities: check if the file exists before trying to
create it again.