naughty: Close 4513: Error: #os-select li button is ambiguous
Known issue which has not occurred in 26 days

Error: #os-select li button is ambiguous

Fixes #4513

Closes #4657