store-tests: Only accept TAP messages on line starts
cockpit's `check-testlib` sometimes causes TAP-like messages to appear
as part of assertions:
```
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-testlib", line 133, in testRetry
    self.assertRegex(stdout, rb"\nnot ok 1 .*test\/verify\/check-example TestExample.testFail # RETRY 1 \(be robust against unstable tests\)\n")
  File "/usr/lib64/python3.10/unittest/case.py", line 1322, in assertRegex
    raise self.failureException(msg)
AssertionError: Regex didn't match: b'\\nnot ok 1 .*test\\/verify\\/check-example TestExample.testFail # RETRY 1 \\(be robust against unstable tests\\)\\n' not found in b'1..2\n# -- [...]
```

This led to our test database now having two 100% failure entries for
TestExample.testFail.

Don't consider these as top-level failures on their own. Tighten the
regular expression to only match at line starts, and parse the whole TAP
line as a single RE.