naughty: Close 5173: tracer crashes: AttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?
Known issue which has not occurred in 25 days

tracer crashes: AttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?

Fixes #5173

Closes #5390