images: Update to new cockpit CI CA certificate
We have to regenerate our CA to make the CA (and its generated
certificates) compatible with OpenSSL 3. The old ones now fail with

> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
> Missing Authority Key Identifier (_ssl.c:1020)