task: Fix task module type annotation for Python 3.6
This is imported from Cockpit's testlib and must be able to run on RHEL 8.
Commit 426759eaf introduced a type annotation which doesn't work with
Python 3.6:

    TypeError: 'type' object is not subscriptable