dispatcher: only close AMQP connection if open
When AMQP drops our connection (which seems to happen once or twice a
week, during the night) we try to handle that with our
on_channel_closed() function which itself calls the main .close() method
on the dispatcher.  Unfortunately, that method, in turn, tries to call
.close() on the connection again, which results in a

  pika.exceptions.ConnectionWrongStateError: Illegal close

which interrupts the close handling, interrupting the normal flow of
events which is supposed to lead to the shutdown of the dispatcher (so
it can be restarted).

Unfortunately, pika schedules the original call via `call_later()` on
the main loop, which captures and prints the exception but doesn't let
it bubble up.  So, ironically, us crashing here prevents the desired
outcome of crashing.  Unfortunately there's not a really nice way to
tell the event loop to let exceptions bubble out: we can set a custom
handler, but the return value is `None` and all of the examples I've
found seem mostly to be about logging exceptions.  It might be possible
to re-raise the exception, but I couldn't find any documentation
suggesting that this is a valid thing to do.

So for now:, let's do the obviously correct thing and check that the
connection is still open before we close it to avoid the exception in
the first place.