prometheus-stats: Fix crash with no data
This was broken in commit 325acc5bd5e which dropped the `or 0`. If there
were no test runs in the last 12 hours, it crashed with

    TypeError: %i format: a number is required, not NoneType