task: Change ellipsis type check for mypy 1.9.0 compatibility
mypy 1.9.0 started failing on this:

> task/github.py:297: error: Incompatible return value type (got "_DT | EllipsisType", expected "_T | _DT")  [return-value]

which is nonsense -- the `default is not ...` explicitly ensures that
we are not returning an ellipsis.

Rewrite this using a type instead of a value check, which works.

Fixes #6271