naughty: Close 5414: tracer crash: AttributeError: module 'platform' has no attribute 'linux_distribution'"
Known issue which has not occurred in 26 days

tracer crash: AttributeError: module 'platform' has no attribute 'linux_distribution'"

Fixes #5414

Closes #5764