github-upload-secrets: Fix crash on nonexisting environments
Robustify the deletion of existing keys for the case that the
environment does not exist at all yet:

```
Traceback (most recent call last):
  File "/var/home/martin/upstream/bots/./github-upload-secrets", line 207, in <module>
    main()
  File "/var/home/martin/upstream/bots/./github-upload-secrets", line 202, in main
    do_deploy_key(api, plus + opts.deploy_to, quad, opts)
  File "/var/home/martin/upstream/bots/./github-upload-secrets", line 142, in do_deploy_key
    upload_deploy_key(api, deploy_to, deploy_from, public, opts)
  File "/var/home/martin/upstream/bots/./github-upload-secrets", line 115, in upload_deploy_key
    for key in keys:
TypeError: 'NoneType' object is not iterable
```