naughty: Close 5410: tracer crash: AttributeError: 'NoneType' object has no attribute 'find_package'" without /etc/os-release
Known issue which has not occurred in 25 days

tracer crash: AttributeError: 'NoneType' object has no attribute 'find_package'" without /etc/os-release

Fixes #5410

Closes #6840