test-scan: fix type error
Just witnessed in CI:

  ERROR:root:Can't find pull request 2
  Traceback (most recent call last):
    File "/__w/bots/bots/./tests-scan", line 425, in <module>
      sys.exit(main())
  	     ^^^^^^
    File "/__w/bots/bots/./tests-scan", line 98, in main
      results = scan_for_pull_tasks(api, opts.context, opts, opts.repo)
  	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/__w/bots/bots/./tests-scan", line 419, in scan_for_pull_tasks
      return [tests_invoke(*x, options=opts) for x in results]
  	   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: 'int' object is not iterable
  ........

This is caused by an invalid `return 1` from a function that ought to
return a list.  Add a type annotation to catch the issue and replace the
error return with a use of `sys.exit()`.